CREATE SCHEMA octans_test COLLATE utf8mb4_general_ci;

USE octans_test;

CREATE TABLE IF NOT EXISTS rol(
	ID_ROL INT UNSIGNED NOT NULL,
	NOMBRE VARCHAR(255),
	PRIMARY KEY(ID_ROL)
);

CREATE TABLE IF NOT EXISTS usuario(
	ID_USUARIO INT UNSIGNED AUTO_INCREMENT,
	ID_ROL INT UNSIGNED NOT NULL,
	NOMBRE VARCHAR(255),
	ACTIVO CHAR(1),
	PRIMARY KEY(ID_USUARIO),
	CONSTRAINT FK_ROL_USUARIO FOREIGN KEY(ID_ROL) REFERENCES rol(ID_ROL)
);

INSERT INTO rol VALUES(1, 'ADMINISTRADOR');
INSERT INTO rol VALUES(2, 'AUDITOR');
INSERT INTO rol VALUES(3, 'AUXILIAR');

